### ISSUE TITLE
Finishing main game

### ISSUE THREAD

**Issue by RockerCaleb1234** [RockerCaleb1234/APCSP#4]
## Layout
- [x] Add a restart system _(Needs testing)_
- [x] Make flagging bombs work
- [x] Add a win/lose system _(Needs testing)_
- [x] Any extra UI improvements _(@ Juan)_

## Library
[Pygame](https://www.pygame.org/docs/) (python)

**Comment by Rodrun** [comment]
Extra UI could be a points display similar to the Microsoft [Minesweeper game from the early 2000’s](https://goo.gl/images/9MHGGj)

**Comment by Rodrun** [comment]
Also, do you want me to make a flag image and commit it

**Comment by Rodrun** [comment]
The extra UI should display remaining cell count. Could be pretty helpful! Also, instead of using static images to display numbers, you should just download a free-to-use font that looks like the classic minesweeper design you mentioned.
